#!/bin/bash 
vol="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)].*/\1/')";
if [ "$vol" = "off" ]; then
	echo $vol
else
	vol="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
	echo "${vol}%"
fi
